/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LavaAxelarIpRPCDistribution__factory } from "./LavaAxelarIpRPCDistribution__factory";
export { LavaNearIpRPCDistribution__factory } from "./LavaNearIpRPCDistribution__factory";
