/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LavaAxelarIpRPCDistribution__factory } from "./LavaAxelarIpRPCDistribution__factory";
export { LavaEvmosIpRPCDistribution__factory } from "./LavaEvmosIpRPCDistribution__factory";
