/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lavaNearIpRpcDistributionSol from "./LavaNearIpRPCDistribution.sol";
export type { lavaNearIpRpcDistributionSol };
export type { LavaAxelarIpRPCDistribution } from "./LavaAxelarIpRPCDistribution";
export type { LavaEvmosIpRPCDistribution } from "./LavaEvmosIpRPCDistribution";
