/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LavaAxelarIpRPCDistribution } from "./LavaAxelarIpRPCDistribution";
export type { LavaEvmosIpRPCDistribution } from "./LavaEvmosIpRPCDistribution";
